services:
  nginx:
    depends_on: 
      - wordpress
    build: ./requirements/nginx/
    ports:
      - "443:443"
    networks:
      - botnet
    volumes:
      - wordpress_vol:/var/www/
    env_file:
      - .env
    restart: on-failure
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    networks:
      - botnet
    volumes:
      - wordpress_vol:/var/www/
    env_file:
      - .env
    restart: on-failure
  mariadb:
    build: ./requirements/mariadb/
    networks:
      - botnet
    volumes:
      - database_vol:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure
networks:
  botnet:
    driver: bridge
volumes:
  database_vol:
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/pschwarz/data/db"
  wordpress_vol:
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/pschwarz/data/www"